<a href="https://colab.research.google.com/github/AlirezaRamezaney/Pytorch-Coding/blob/main/TorchAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[1 2 3]


In [ ]:
!pip list

In [8]:
import torch
import numpy as np


tensor_2d = torch.randn(3,4)
tensor_2d

tensor_3d = torch.zeros(2,3,4)
tensor_3d

A = np.array([1, 2, 3])
tensor_fromNUMPY = torch.tensor(A)
tensor_fromNUMPY

my_torch = torch.arange(10)
my_torch = my_torch.reshape(2,-1)
my_torch[:,3]

B = torch.tensor([3, 4, 5, 6])
C = torch.tensor([7, 8, 9, 10])

D = B + C
B = B.add(C)
print("{0}  \n  {1}".format(D,B))


tensor([10, 12, 14, 16])  
  tensor([10, 12, 14, 16])
